services:
  database:
    image: postgres
    container_name: donus_code_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=donus
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
